spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: kjw123456.
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://@dataBaseHost@:3306/@mysqlDataBase@?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  dubbo:
    appname: dao
    registry: @dubboRegistry@
    protocol: dubbo
    port: @daoDubboPort@
    server: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
