spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: kjw123456.
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://@dataBaseHost@:3306/@mysqlDataBase@?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
  redis:
    host: @dataBaseHost@
    port: 6379
    password: kjw123456.
    timeout: 5000
    database: @redisDataBase@
  task:
    scheduling:
      pool:
        size: 5