server:
  port: 80
  servlet:
    context-path: /weixin
spring:
  dubbo:
    port: @wechatDubboPort@
    protocol: dubbo
    appname: wechat
    registry: @dubboRegistry@
  redis:
    host: @dataBaseHost@
    port: 6379
    password: kjw123456.
    timeout: 5000
    database: @redisDataBase@
#########################配置类读取的字段#######################
wechat:
  app-id: @wechatAppId@
  secret: @wechatSecret@
  aes-key: @wechatAesKey@
  token: @wechatToken@
